### PR TITLE
Return cluster names in clusters details

### PR DESCRIPTION
**Pull request by joselsegura**
# Description

Adding the "cluster_name" in the response of the cluster_details endpoint, added to the existing cluster_id.

## Type of change
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## Testing steps

Testes though local environment and unit tests

## Checklist
* [x] `make before_commit` passes
* [x] updated documentation wherever necessary
* [x] added or modified tests if necessary
* [x] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by juandspy — APPROVED** [review]

**Comment by Bee-lee** [comment]
please also update OpenAPI spec

**Comment by joselsegura** [comment]
> please also update OpenAPI spec

It was already updated: https://github.com/RedHatInsights/insights-results-smart-proxy/blob/8de6370044c9d330369f35b3a1c874ee3b9b2f31/server/api/v2/openapi.json#L841

This is because the internal data struct used by the response was updated already, so the response was including the clustern_name, but it will be empty until this PR is merged

**Review by Bee-lee — COMMENTED** [review]
looks ok, are we sure this is not a breaking change for the UI? I know its still a list of structs with an extra field, but maybe it would be worth to check? esp. considering it's already used in prod beta

**Review by dpensi — APPROVED** [review]

**Review by dpensi — APPROVED** [review]

**Review by tisnik — COMMENTED** [review]
Does it change the REST API?

**Comment by joselsegura** [comment]
> looks ok, are we sure this is not a breaking change for the UI? I know its still a list of structs with an extra field, but maybe it would be worth to check? esp. considering it's already used in prod beta

I don't have experience with the Advisor UI. How can I check it? In addition, which backend environment is used by prod beta?

**Comment by joselsegura** [comment]
> Does it change the REST API?

No, it doesn't. The API is already returning the field, but always with empty value

**Review by tisnik — APPROVED** [review]
ok

**Comment by tisnik** [comment]
> > Does it change the REST API?
> 
> No, it doesn't. The API is already returning the field, but always with empty value

ok then :)

do you plan to add some REST API test?

**Comment by joselsegura** [comment]
> > > Does it change the REST API?
> > 
> > 
> > No, it doesn't. The API is already returning the field, but always with empty value
> 
> ok then :)
> 
> do you plan to add some REST API test?

I didn plan it yet, I will create a task for it (I will need to create the whole rest_api_tests skeleton because it doesn't exist for this repo)

**Pull request merged**
