### PR TITLE
Lower log level to reduce number of logs in prod

### PR DESCRIPTION
**Pull request by Bee-lee**
# Description
- reduce log level from INFO to DEBUG for a lot of log messages
- kept INFO level for logs which are very useful for regular testing
- corrected log level from INFO to ERROR where applicable
- removed a couple of useless logs or logs previously used to debug no longer relevant issues

Fixes https://issues.redhat.com/browse/CCXDEV-11350

## Type of change

Please delete options that are not relevant.

- Refactor (refactoring code, removing useless files)

## Testing steps
n/a

## Checklist
* [x] `make before_commit` passes
* [x] updated documentation wherever necessary
* [x] added or modified tests if necessary
* [x] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by matysek — APPROVED** [review]
/lgtm

**Review by epapbak — APPROVED** [review]
ty!

**Pull request merged**
