### PR TITLE
Drop support for `jwt` auth type

### PR DESCRIPTION
**Pull request by Bee-lee**
# Description
`jwt` auth type is not used in any real environment, all environments use `xrh` auth type and using JWT is not supported at all.

Fixes CCXDEV-9369

## Type of change

Please delete options that are not relevant.

- Refactor (refactoring code, removing useless files)
- Unit tests (no changes in the code)
- Configuration update

## Testing steps
`make before_commit`

## Checklist
* [x] `make before_commit` passes
* [x] updated documentation wherever necessary
* [x] added or modified tests if necessary
* [x] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
LGTM

**Comment by Bee-lee** [comment]
@matysek the test is still failing even though it's marked with an IQE blocker for ephemeral, I don't think I understand why

**Review by epapbak — APPROVED** [review]

**Review by joselsegura — APPROVED** [review]

**Pull request merged**
