### PR TITLE
Io pulling sequence diagram

### LINKED ISSUE #234: Create sequence diagram for data flow from data pipeline to OCP WebConsole
Create sequence diagram for data flow from data pipeline to OCP WebConsole

### PR DESCRIPTION
**Pull request by tisnik**
# Description

Create sequence diagram for data flow from data pipeline to OCP WebConsole

Fixes #234

## Type of change

- Documentation update

## Testing steps

N/A

### CODE REVIEW

**Comment by quarckster** [comment]
@tisnik should the diagtam be reversed. OCP Webconsole on the left and Smart Proxy on the right?

**Review by natiiix — APPROVED** [review]
Looks nice! :+1:

**Review by joselsegura — APPROVED** [review]
Just to be clear: when we talk about "IO memory cache" you are referring to a variable that stores the content of the latest report retrieved from Smart Proxy, am I getting it right?

**Comment by tisnik** [comment]
> Just to be clear: when we talk about "IO memory cache" you are referring to a variable that stores the content of the latest report retrieved from Smart Proxy, am I getting it right?

yes,  ie. no rocket science-based cache :)

**Pull request merged**
